/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.papyrus.requirements.sysml14


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BoilerplateTextStandaloneSetup extends BoilerplateTextStandaloneSetupGenerated {

	def static void doSetup() {
		new BoilerplateTextStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
