/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.papyrus.requirements.sysml14.ide


/**
 * Use this class to register ide components.
 */
class BoilerplateTextIdeModule extends AbstractBoilerplateTextIdeModule {
}
