<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="proxy" nsURI="http://org.eclipse.papyrus/proxy" nsPrefix="Proxy">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="Proxy"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreReference" eSuperTypes="#//Proxy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" ordered="false" eType="ecore:EClass ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proxy" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Element" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileReference" eSuperTypes="#//Proxy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" ordered="false" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral=" "/>
  </eClassifiers>
</ecore:EPackage>
