<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BMMProfile" nsURI="https://www.eclipse.org/papyrus/BMM/0.7.0/"
    nsPrefix="Bmm">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="Bmm"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MotivationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Artifact" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assessment" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnit" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="#//CourseOfAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfAction" eSuperTypes="#//Means"/>
  <eClassifiers xsi:type="ecore:EClass" name="Means" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Directive" eSuperTypes="#//Means"/>
  <eClassifiers xsi:type="ecore:EClass" name="PotentialImpact" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Regulation" eSuperTypes="#//ExternalInfluencer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalInfluencer" eSuperTypes="#//Influencer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Influencer" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfluencingOrganization" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationCategory" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfluencerCategory" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DesiredResult" eSuperTypes="#//End"/>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DesiredResultCategory" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcess" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRule" eSuperTypes="#//Directive"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPolicy" eSuperTypes="#//Directive"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tactic" eSuperTypes="#//CourseOfAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Offering" eSuperTypes="#//FixedAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="FixedAsset" eSuperTypes="#//Asset"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Asset"/>
  <eClassifiers xsi:type="ecore:EClass" name="Liability" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mission" eSuperTypes="#//Means"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vision" eSuperTypes="#//End"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//DesiredResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="Objective" eSuperTypes="#//DesiredResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentCategory" eSuperTypes="#//MotivationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalInfluencer" eSuperTypes="#//Influencer"/>
  <eClassifiers xsi:type="ecore:EClass" name="PotentialReward" eSuperTypes="#//PotentialImpact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Risk" eSuperTypes="#//PotentialImpact"/>
  <eClassifiers xsi:type="ecore:EClass" name="MotivationEdge" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsingAssessmentUsesUsedAssessment" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitMakesAssessment" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentCategoryCategorizesAssessment"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentIdentifiesPotentialImpact"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentAffectsAchievementOfEnd" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentAffectsEmploymentOfMeans"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentProvidesImpetusForDirective"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentIsJudgmentOfInfluencer" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderAssessmentCategoryCategorizesNarrowerAssessmentCategory"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessManagesAsset" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitIsResponsibleForAsset"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfActionDeploysAsset" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectiveGovernsUseOfAsset" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderBusinessPolicyIncludesMoreSpecificBusinessPolicy"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPolicyIsBasisOfBusinessRule"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPolicyGovernsBusinessProcess"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitIsResponsibleForBusinessProcess"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRuleGuidesBusinessProcess" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessRealizesCourseOfAction"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessDeliversOffering" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="TacticEffectsEnforcementLevelOfBusinessRule"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectiveGovernsCourseOfAction" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderCourseOfActionIncludesMoreSpecificCourseOfAction"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnablingCourseOfActionEnablesEnabledCourseOfAction"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfActionIsFormulatedBasedOnDirective"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfActionDefinesOffering" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfActionDischargesLiability" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfActionChannelsEffortsTowardsDesiredResult"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderDesiredResultIncludesMoreSpecificDesiredResult"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DesiredResultCategoryCategorizesDesiredResult"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectiveSupportsAchievementOfDesiredResult"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderDesiredCategoryCategorizesMoreSpecificDesiredResultCategory"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="PotentialImpactProvidesImpetursForDirective"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectiveActsAsRegulation" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitDefinesEnd" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OfferingUsesFixedAsset" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="FixedAssetProvidesResource" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectiveQuantitiesGoal" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalAmplifiesVision" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitRecognizesInfluencer"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfluencingOrganizationIsSourceofInfluencer"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfluencerCategoryCategorizesInfluencer"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderInfluencerCategorizesNarrowerInfluencerCategory"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationCategoryCategorizesInfluencingOrganization"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitActsAsInfluencingOrganization"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitIsResponsibleForLiability"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiabilityClaimsResource" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnitEstablishesMeans" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrategyIsAComponentfOfThe_PlanForMIssion"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="MissionMakesOperativeVision" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="OfferingRequiresResource" eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="BroaderOrganizationCategoryCategorizesNarrowerOrganizationCategory"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrategyDeterminesOrganizationUnit"
      eSuperTypes="#//MotivationEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="TacticImplementsStrategy" eSuperTypes="#//MotivationEdge"/>
</ecore:EPackage>
