/**
 * ****************************************************************************
 * Copyright (c) 2017 CEA LIST.
 *  *
 *  *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *  *
 * Contributors:
 * 
 * 		Mauricio Alferez (mauricio.alferez@cea.fr) CEA LIST - Initial API and implementation
 *  *
 *  ****************************************************************************
 * 
 * generated by Xtext 2.11.0
 */
package org.eclipse.papyrus.requirements.sysml14.boilerplateText;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.BoilerplateTextFactory
 * @model kind="package"
 * @generated
 */
public interface BoilerplateTextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "boilerplateText";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.eclipse.org/papyrus/requirements/sysml14/BoilerplateText";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "boilerplateText";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BoilerplateTextPackage eINSTANCE = org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl.init();

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ModelImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.RequirementImpl <em>Requirement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.RequirementImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getRequirement()
   * @generated
   */
  int REQUIREMENT = 1;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__PREFIX = 0;

  /**
   * The feature id for the '<em><b>System</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__SYSTEM = 1;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__PREDICATE = 2;

  /**
   * The number of structural features of the '<em>Requirement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.SubjectImpl <em>Subject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.SubjectImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getSubject()
   * @generated
   */
  int SUBJECT = 2;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__SYSTEM = 0;

  /**
   * The number of structural features of the '<em>Subject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PrefixImpl <em>Prefix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PrefixImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getPrefix()
   * @generated
   */
  int PREFIX = 3;

  /**
   * The number of structural features of the '<em>Prefix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.IfImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getIf()
   * @generated
   */
  int IF = 4;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__EVENT = PREFIX_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = PREFIX_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.WhileImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 5;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__STATE = PREFIX_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = PREFIX_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PredicateImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 6;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__ACTION = 0;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotAllowImpl <em>Shall Not Allow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotAllowImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShallNotAllow()
   * @generated
   */
  int SHALL_NOT_ALLOW = 7;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_NOT_ALLOW__ACTION = PREDICATE__ACTION;

  /**
   * The feature id for the '<em><b>Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_NOT_ALLOW__ENTITY = PREDICATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action Performed By Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_NOT_ALLOW__ACTION_PERFORMED_BY_ENTITY = PREDICATE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Shall Not Allow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_NOT_ALLOW_FEATURE_COUNT = PREDICATE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallAllowImpl <em>Shall Allow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallAllowImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShallAllow()
   * @generated
   */
  int SHALL_ALLOW = 8;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_ALLOW__ACTION = PREDICATE__ACTION;

  /**
   * The feature id for the '<em><b>Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_ALLOW__ENTITY = PREDICATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action Performed By Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_ALLOW__ACTION_PERFORMED_BY_ENTITY = PREDICATE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Shall Allow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_ALLOW_FEATURE_COUNT = PREDICATE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotImpl <em>Shall Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShallNot()
   * @generated
   */
  int SHALL_NOT = 9;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_NOT__ACTION = PREDICATE__ACTION;

  /**
   * The number of structural features of the '<em>Shall Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_NOT_FEATURE_COUNT = PREDICATE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallImpl <em>Shall</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallImpl
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShall()
   * @generated
   */
  int SHALL = 10;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL__ACTION = PREDICATE__ACTION;

  /**
   * The number of structural features of the '<em>Shall</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHALL_FEATURE_COUNT = PREDICATE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Model</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement <em>Requirement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Requirement</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement
   * @generated
   */
  EClass getRequirement();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prefix</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement#getPrefix()
   * @see #getRequirement()
   * @generated
   */
  EReference getRequirement_Prefix();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>System</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement#getSystem()
   * @see #getRequirement()
   * @generated
   */
  EReference getRequirement_System();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Requirement#getPredicate()
   * @see #getRequirement()
   * @generated
   */
  EReference getRequirement_Predicate();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Subject <em>Subject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subject</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Subject
   * @generated
   */
  EClass getSubject();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Subject#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>System</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Subject#getSystem()
   * @see #getSubject()
   * @generated
   */
  EAttribute getSubject_System();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Prefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prefix</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Prefix
   * @generated
   */
  EClass getPrefix();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the attribute list '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.If#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Event</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.If#getEvent()
   * @see #getIf()
   * @generated
   */
  EAttribute getIf_Event();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.While#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.While#getState()
   * @see #getWhile()
   * @generated
   */
  EAttribute getWhile_State();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Predicate#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Predicate#getAction()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Action();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNotAllow <em>Shall Not Allow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shall Not Allow</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNotAllow
   * @generated
   */
  EClass getShallNotAllow();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNotAllow#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Entity</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNotAllow#getEntity()
   * @see #getShallNotAllow()
   * @generated
   */
  EAttribute getShallNotAllow_Entity();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNotAllow#getActionPerformedByEntity <em>Action Performed By Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action Performed By Entity</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNotAllow#getActionPerformedByEntity()
   * @see #getShallNotAllow()
   * @generated
   */
  EAttribute getShallNotAllow_ActionPerformedByEntity();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallAllow <em>Shall Allow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shall Allow</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallAllow
   * @generated
   */
  EClass getShallAllow();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallAllow#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Entity</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallAllow#getEntity()
   * @see #getShallAllow()
   * @generated
   */
  EAttribute getShallAllow_Entity();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallAllow#getActionPerformedByEntity <em>Action Performed By Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action Performed By Entity</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallAllow#getActionPerformedByEntity()
   * @see #getShallAllow()
   * @generated
   */
  EAttribute getShallAllow_ActionPerformedByEntity();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNot <em>Shall Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shall Not</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.ShallNot
   * @generated
   */
  EClass getShallNot();

  /**
   * Returns the meta object for class '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.Shall <em>Shall</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shall</em>'.
   * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.Shall
   * @generated
   */
  EClass getShall();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BoilerplateTextFactory getBoilerplateTextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ModelImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.RequirementImpl <em>Requirement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.RequirementImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getRequirement()
     * @generated
     */
    EClass REQUIREMENT = eINSTANCE.getRequirement();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENT__PREFIX = eINSTANCE.getRequirement_Prefix();

    /**
     * The meta object literal for the '<em><b>System</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENT__SYSTEM = eINSTANCE.getRequirement_System();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENT__PREDICATE = eINSTANCE.getRequirement_Predicate();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.SubjectImpl <em>Subject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.SubjectImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getSubject()
     * @generated
     */
    EClass SUBJECT = eINSTANCE.getSubject();

    /**
     * The meta object literal for the '<em><b>System</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBJECT__SYSTEM = eINSTANCE.getSubject_System();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PrefixImpl <em>Prefix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PrefixImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getPrefix()
     * @generated
     */
    EClass PREFIX = eINSTANCE.getPrefix();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.IfImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF__EVENT = eINSTANCE.getIf_Event();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.WhileImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHILE__STATE = eINSTANCE.getWhile_State();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.PredicateImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__ACTION = eINSTANCE.getPredicate_Action();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotAllowImpl <em>Shall Not Allow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotAllowImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShallNotAllow()
     * @generated
     */
    EClass SHALL_NOT_ALLOW = eINSTANCE.getShallNotAllow();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHALL_NOT_ALLOW__ENTITY = eINSTANCE.getShallNotAllow_Entity();

    /**
     * The meta object literal for the '<em><b>Action Performed By Entity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHALL_NOT_ALLOW__ACTION_PERFORMED_BY_ENTITY = eINSTANCE.getShallNotAllow_ActionPerformedByEntity();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallAllowImpl <em>Shall Allow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallAllowImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShallAllow()
     * @generated
     */
    EClass SHALL_ALLOW = eINSTANCE.getShallAllow();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHALL_ALLOW__ENTITY = eINSTANCE.getShallAllow_Entity();

    /**
     * The meta object literal for the '<em><b>Action Performed By Entity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHALL_ALLOW__ACTION_PERFORMED_BY_ENTITY = eINSTANCE.getShallAllow_ActionPerformedByEntity();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotImpl <em>Shall Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallNotImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShallNot()
     * @generated
     */
    EClass SHALL_NOT = eINSTANCE.getShallNot();

    /**
     * The meta object literal for the '{@link org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallImpl <em>Shall</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.ShallImpl
     * @see org.eclipse.papyrus.requirements.sysml14.boilerplateText.impl.BoilerplateTextPackageImpl#getShall()
     * @generated
     */
    EClass SHALL = eINSTANCE.getShall();

  }

} //BoilerplateTextPackage
