/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.papyrus.requirements.sysml14.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BoilerplateTextUiModule extends AbstractBoilerplateTextUiModule {
}
