/*****************************************************************************
 * Copyright (c) 2017 CEA LIST.
 *
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * 
 * 		Mauricio Alferez (mauricio.alferez@cea.fr) CEA LIST - Initial API and implementation
 *
 *****************************************************************************/
/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.papyrus.requirements.sysml14.ui;

import com.google.inject.Injector;
import org.eclipse.papyrus.requirements.sysml14.boilerplatetext.ui.internal.BoilerplatetextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BoilerplateTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BoilerplatetextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BoilerplatetextActivator.getInstance().getInjector(BoilerplatetextActivator.ORG_ECLIPSE_PAPYRUS_REQUIREMENTS_SYSML14_BOILERPLATETEXT);
	}
	
}
